name: Playwright Tests via Docker

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          load: true                 
          tags: playwright-tests:latest

      - name: Run Playwright tests
        run: docker run playwright-tests:latest
