name: Playwright Tests via Docker
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker Image
      uses: docker/build-push=action@v4
      with:
        context: .
        file: Dockerfile
        push: false
        tag: playwright-tests:latest

    - name: Run test
      run: 
        docker run playwright-tests:latest